# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: jawslab
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-njs-api

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}  # Default to 'dev' stage if not specified
  environment:
    DATABASE_URL: ${env:DATABASE_URL, "fallback value"}
  iam:
    role:
      name: serverless-api-lambda-ssm-role # Name of IAM role to use with this Lambda function
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: "*"
        - Effect: Allow
          Action:
            - ssm:GetParameter
            - ssm:GetParameters
            - ssm:GetParametersByPath
            - ssm:DescribeParameters
            - ssm:GetParameterHistory
          Resource: "*"
plugins:
  - serverless-offline
  - serverless-dotenv-plugin
custom:
  dotenv:
    # Automatically load .env files for each stage
    path: .env.${self:provider.stage}
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - DATABASE_URL

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: "*"
